import React from 'react';

const IdeasPage = () => {
    
    const ideasArray = [
        "english",
        "english, grammar",
        "english, composition",
        "reading, patience",
        "reading, comprehension",
        "food",
        "politic",
        "politics",
        "government, United States",
        "government, local",
        "math",
        "math, basic",
        "math, algebra",
        "math, calculus",
        "computer, programming languages",
        "computer, hardware",
        "computer, peripherals",
        "science, computer",
        "shopping",
        "entertainment, vacation",
        "entertainment, ice skating",
        "entertainment, music",
        "entertainment, christian music",
        "cars",
        "vacation",
        "work",
        "love",
        "church, baptism of John the baptist",
        "church, baptism from Jesus Christ",
        "church, Jesus Christ's feet washing ministry",
        "church, forgiveness",
        "church, eternal life",
        "church, catholic communion",
        "church, catholic confirmation",
        "church, testimonies",
        "church, Jesus Christ",
        "church, Holy Father God",
        "church, Kingdom of God",
        "church, Jesus Christ said his Kingdom is not of this world",
        "church, ministry",
        "church, love",
        "church, prayer",
        "church, cardinal",
        "church, Pope Francis",
        "church, Pope Leo XIV",
        "church, vatican",
        "church, conclave",
        "church, help",
        "church, Faith",
        "church, Hope",
        "church, Love",
        "church, Cross",
        "church, Jesus Christ Crucified",
        "church, Know Jesus Christ and him Crucified",
        "church, Know Holy Father God in Heaven",
        "mountains",
        "rest stops",
        "pharmacy",
        "weather",
        "countries",
        "cities",
        "towns",
        "hamlets",
        "real estate",
        "bus, ride",
        "maps, country",
        "maps, city",
        "maps, driving",
        "maps, directions",
        "maps, local",
        "church, Saints",
        "church, Repent",
        "church, Repentance",
        "movies, actresses",
        "movies, actors",
        "movies, titles",
        "sports, athletes",
        "sports, team",
        "sports, individual",
        "sport, athletes",
        "health",
        "furniture",
        "cooking, supplies",
        "cooking, recipes",
        "sports, golf",
        "sports, tennis",
        "taxi",
        "animals",
        "phone, cellular",
        "phone, landline",
        "writing",
        "writing, grammar",
        "writing, essay",
        "writing, book",
        "writing, novel",
        "writing, paper",
        "writing, word processing",
        "information Informatics",
        "hospitals",
        "charity, giving",
        "thinking",
        "thinking, philosophy",
        "thinking, imagination (good accurate use of)",
        "thinking, imagination",
        "thinking, words",
        "thinking, study",
        "thinking, worry",
        "thinking, psychology",
        "thinking, sociology",
        "thinking, well",
        "thinking, christianity",
        "thinking, patience",
        "feeling, patience",
        "feeling, emotions",
        "thinking, grammar",
        "dictionary",
        "dinosaurs",
        "church",
        "church, catholic",
        "church, denominational",
        "church, non denominational",
        "church, Gospel of Grace",
        "church, Gospel of the Kingdom",
        "holy bible, KJV",
        "holy bible, study",
        "housing",
        "schools, colleges",
        "fishing, ministry",
        "fishing, stream",
        "fishing, lake",
        "movies",
        "christian",
        "christian, testimonies",
        "walking",
        "dogs",
        "dogs, food",
        "cats",
        "cats, food",
        "pets",
        "prayer",
        "ethics",
        "morals",
        "pets, food",
        "airports",
        "airports, car rental", 
        "car rental", 
        "hotels",
        "motels",
        "laundry",
        "grocery",
        "sports",
        "sports, running",
        "sports, baseball",
        "sports, soccer",
        "sports, football",
        "sports, swimming",
        "sports, ice skating",
        "sports, race walking",
        "sports, elite",
        "sports, recreational",
        "sports, hiking",
        "sports, rugby",
        "sports, cricket",
        "sports, olympics",
        "ai, robots",
        "ai, artificial inteligence",
        "ai, convolutional neural networks",
        "ai, natural language"
    ]
    
     return(
     
     <div>
      <div className="margin-bottom-5a">Subect Ideas which can be used as hash tags, for example Chariity, Giving, #charitygiving</div>
<ul className="">
      {ideasArray.sort().map((item, index) => (
        <li key={index}>{item}</li>
      ))}
    </ul>
     </div>
     
    
  )   
};

export default IdeasPage;